spring:
    application:
        name: poc
    cloud:
        openfeign:
            client:
                config:
                    default:
                        connectTimeout: 5000
                        readTimeout: 5000
                        loggerLevel: basic
        azure:
          servicebus:
            namespace: sbemulatorns
            entity-type: queue
            connection-string: Endpoint=sb://servicebus-emulator;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
          credential:
            managed-identity-enabled: false
    datasource:
      url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
      username: sa
      password:
      driver-class-name: org.h2.Driver
      console:
        enabled: true
      hikari:
        pool-name: H2HikariPool
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 30000
        max-lifetime: 1800000
        connection-timeout: 30000
        leak-detection-threshold: 2000
        validation-timeout: 5000